// 
// Copyright 2025 Andrew Haisley
// 
// This program is free software: you can redistribute it and/or modify it under the terms 
// of the GNU General Public License as published by the Free Software Foundation, either 
// version 3 of the License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
// See the GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License along with this program. 
// If not, see https://www.gnu.org/licenses/.
// 
/**
 * automatically generated by rrgen.py at 05:05PM on January 30, 2024 do not edit by hand.
 */

#include <boost/lexical_cast.hpp>

#include "types.hpp"
#include "util.hpp"
#include "buffer.hpp"
#include "dns_type_bitmap.hpp"
#include "dns_rr_HTTPS.hpp"

using namespace adns;
using namespace std;

dns_rr_HTTPS::dns_rr_HTTPS() : dns_rr()
{
    set_type(dns_rr::T_HTTPS_e);
}

dns_rr_HTTPS::~dns_rr_HTTPS()
{
}

dns_rr *dns_rr_HTTPS::clone()
{
    return new dns_rr_HTTPS(*this);
}

void dns_rr_HTTPS::json_serialize() const
{
    dns_rr::json_serialize();
    set_json("priority", int(get_priority()));
    set_json("target", get_target()->to_string());
    set_json("svcparams", get_svcparams()->to_json());

}

void dns_rr_HTTPS::json_unserialize() 
{
    m_priority = int((*m_json_object)["priority"]);
    m_target = make_shared<dns_name>((*m_json_object)["target"]);
    m_svcparams = make_shared<dns_svcparams>((*m_json_object)["svcparams"]);

}

void dns_rr_HTTPS::set_priority(unsigned short priority)
{
    m_priority = priority;
}
void dns_rr_HTTPS::set_target(const std::shared_ptr<dns_name> &target)
{
    m_target = target;
}
void dns_rr_HTTPS::set_svcparams(const std::shared_ptr<dns_svcparams> &svcparams)
{
    m_svcparams = svcparams;
}

unsigned short dns_rr_HTTPS::get_priority() const
{
    return m_priority;
}
const std::shared_ptr<dns_name> &dns_rr_HTTPS::get_target() const
{
    return m_target;
}
const std::shared_ptr<dns_svcparams> &dns_rr_HTTPS::get_svcparams() const
{
    return m_svcparams;
}


void dns_rr_HTTPS::dump() const
{
    LOG(debug) << to_string();
}

string dns_rr_HTTPS::to_string() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + boost::lexical_cast<string>(get_ttl()) + " " + boost::lexical_cast<string>(get_priority()) + " " + get_target()->to_string() + " " + get_svcparams()->to_string();
}

string dns_rr_HTTPS::to_string_no_ttl() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + boost::lexical_cast<string>(get_priority()) + " " + get_target()->to_string() + " " + get_svcparams()->to_string();
}
