// 
// Copyright 2025 Andrew Haisley
// 
// This program is free software: you can redistribute it and/or modify it under the terms 
// of the GNU General Public License as published by the Free Software Foundation, either 
// version 3 of the License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
// See the GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License along with this program. 
// If not, see https://www.gnu.org/licenses/.
// 
/**
 * automatically generated by rrgen.py at 05:05PM on January 30, 2024 do not edit by hand.
 */

#include <boost/lexical_cast.hpp>

#include "types.hpp"
#include "util.hpp"
#include "buffer.hpp"
#include "dns_type_bitmap.hpp"
#include "dns_rr_CSYNC.hpp"

using namespace adns;
using namespace std;

dns_rr_CSYNC::dns_rr_CSYNC() : dns_rr()
{
    set_type(dns_rr::T_CSYNC_e);
}

dns_rr_CSYNC::~dns_rr_CSYNC()
{
}

dns_rr *dns_rr_CSYNC::clone()
{
    return new dns_rr_CSYNC(*this);
}

void dns_rr_CSYNC::json_serialize() const
{
    dns_rr::json_serialize();
    set_json("soa_serial", int(get_soa_serial()));
    set_json("flags", int(get_flags()));
    set_json("type_bitmap", get_type_bitmap()->to_json());

}

void dns_rr_CSYNC::json_unserialize() 
{
    m_soa_serial = int((*m_json_object)["soa_serial"]);
    m_flags = int((*m_json_object)["flags"]);
    m_type_bitmap = make_shared<dns_type_bitmap>((*m_json_object)["type_bitmap"]);

}

void dns_rr_CSYNC::set_soa_serial(uint soa_serial)
{
    m_soa_serial = soa_serial;
}
void dns_rr_CSYNC::set_flags(unsigned short flags)
{
    m_flags = flags;
}
void dns_rr_CSYNC::set_type_bitmap(const std::shared_ptr<dns_type_bitmap> &type_bitmap)
{
    m_type_bitmap = type_bitmap;
}

uint dns_rr_CSYNC::get_soa_serial() const
{
    return m_soa_serial;
}
unsigned short dns_rr_CSYNC::get_flags() const
{
    return m_flags;
}
const std::shared_ptr<dns_type_bitmap> &dns_rr_CSYNC::get_type_bitmap() const
{
    return m_type_bitmap;
}


void dns_rr_CSYNC::dump() const
{
    LOG(debug) << to_string();
}

string dns_rr_CSYNC::to_string() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + boost::lexical_cast<string>(get_ttl()) + " " + boost::lexical_cast<string>(get_soa_serial()) + " " + boost::lexical_cast<string>(get_flags()) + " " + get_type_bitmap()->to_string();
}

string dns_rr_CSYNC::to_string_no_ttl() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + boost::lexical_cast<string>(get_soa_serial()) + " " + boost::lexical_cast<string>(get_flags()) + " " + get_type_bitmap()->to_string();
}
