//
//  Copyright 2025 Andrew Haisley
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and 
//  associated documentation files (the “Software”), to deal in the Software without restriction, 
//  including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
//  and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, 
//  subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all copies or substantial 
//  portions of the Software.
//
//  THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT 
//  NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
//  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
//  WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
//  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
 
/**
 * automatically generated by rrgen.py at 05:05PM on January 30, 2024 do not edit by hand.
 */

#include <boost/lexical_cast.hpp>

#include "types.hpp"
#include "util.hpp"
#include "buffer.hpp"
#include "dns_type_bitmap.hpp"
#include "dns_rr_IPSECKEY.hpp"

using namespace adns;
using namespace std;

dns_rr_IPSECKEY::dns_rr_IPSECKEY() : dns_rr()
{
    set_type(dns_rr::T_IPSECKEY_e);
}

dns_rr_IPSECKEY::~dns_rr_IPSECKEY()
{
}

dns_rr *dns_rr_IPSECKEY::clone()
{
    return new dns_rr_IPSECKEY(*this);
}

void dns_rr_IPSECKEY::json_serialize() const
{
    dns_rr::json_serialize();
    set_json("ipseckey", get_ipseckey()->to_json());

}

void dns_rr_IPSECKEY::json_unserialize() 
{
    m_ipseckey = make_shared<dns_ipseckey>((*m_json_object)["ipseckey"]);

}

void dns_rr_IPSECKEY::set_ipseckey(const std::shared_ptr<dns_ipseckey> &ipseckey)
{
    m_ipseckey = ipseckey;
}

const std::shared_ptr<dns_ipseckey> &dns_rr_IPSECKEY::get_ipseckey() const
{
    return m_ipseckey;
}


void dns_rr_IPSECKEY::dump() const
{
    LOG(debug) << to_string();
}

string dns_rr_IPSECKEY::to_string() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + boost::lexical_cast<string>(get_ttl()) + " " + get_ipseckey()->to_string();
}

string dns_rr_IPSECKEY::to_string_no_ttl() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + get_ipseckey()->to_string();
}
