// 
// Copyright 2025 Andrew Haisley
// 
// This program is free software: you can redistribute it and/or modify it under the terms 
// of the GNU General Public License as published by the Free Software Foundation, either 
// version 3 of the License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
// See the GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License along with this program. 
// If not, see https://www.gnu.org/licenses/.
// 
/**
 * automatically generated by rrgen.py at 05:05PM on January 30, 2024 do not edit by hand.
 */

#include <boost/lexical_cast.hpp>

#include "types.hpp"
#include "util.hpp"
#include "buffer.hpp"
#include "dns_type_bitmap.hpp"
#include "dns_rr_NS.hpp"

using namespace adns;
using namespace std;

dns_rr_NS::dns_rr_NS() : dns_rr()
{
    set_type(dns_rr::T_NS_e);
}

dns_rr_NS::~dns_rr_NS()
{
}

dns_rr *dns_rr_NS::clone()
{
    return new dns_rr_NS(*this);
}

void dns_rr_NS::json_serialize() const
{
    dns_rr::json_serialize();
    set_json("nsdname", get_nsdname()->to_string());

}

void dns_rr_NS::json_unserialize() 
{
    m_nsdname = make_shared<dns_name>((*m_json_object)["nsdname"]);

}

void dns_rr_NS::set_nsdname(const std::shared_ptr<dns_name> &nsdname)
{
    m_nsdname = nsdname;
}

const std::shared_ptr<dns_name> &dns_rr_NS::get_nsdname() const
{
    return m_nsdname;
}


void dns_rr_NS::dump() const
{
    LOG(debug) << to_string();
}

string dns_rr_NS::to_string() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + boost::lexical_cast<string>(get_ttl()) + " " + get_nsdname()->to_string();
}

string dns_rr_NS::to_string_no_ttl() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + get_nsdname()->to_string();
}
