//
//  Copyright 2025 Andrew Haisley
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and 
//  associated documentation files (the “Software”), to deal in the Software without restriction, 
//  including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
//  and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, 
//  subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all copies or substantial 
//  portions of the Software.
//
//  THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT 
//  NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
//  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
//  WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
//  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
 
/**
 * automatically generated by rrgen.py at 02:39PM on November 03, 2025 do not edit by hand.
 */

#include <boost/lexical_cast.hpp>

#include "types.hpp"
#include "util.hpp"
#include "buffer.hpp"
#include "dns_type_bitmap.hpp"
#include "dns_rr_CAA.hpp"

using namespace adns;
using namespace std;

dns_rr_CAA::dns_rr_CAA() : dns_rr()
{
    set_type(dns_rr::T_CAA_e);
}

dns_rr_CAA::~dns_rr_CAA()
{
}

dns_rr *dns_rr_CAA::clone()
{
    return new dns_rr_CAA(*this);
}

void dns_rr_CAA::json_serialize() const
{
    dns_rr::json_serialize();
    set_json("flags", int(get_flags()));
    set_json("tag", get_tag()->to_string());
    set_json("contents", util::tobase64(get_contents()));

}

void dns_rr_CAA::json_unserialize() 
{
    m_flags = int((*m_json_object)["flags"]);
    m_tag = make_shared<dns_label>((*m_json_object)["tag"]);
    m_contents = util::frombase64((*m_json_object)["contents"]);

}

void dns_rr_CAA::set_flags(octet flags)
{
    m_flags = flags;
}
void dns_rr_CAA::set_tag(const std::shared_ptr<dns_label> &tag)
{
    m_tag = tag;
}
void dns_rr_CAA::set_contents(const buffer &contents)
{
    m_contents = contents;
}

octet dns_rr_CAA::get_flags() const
{
    return m_flags;
}
const std::shared_ptr<dns_label> &dns_rr_CAA::get_tag() const
{
    return m_tag;
}
const buffer &dns_rr_CAA::get_contents() const
{
    return m_contents;
}


void dns_rr_CAA::dump() const
{
    LOG(debug) << to_string();
}

string dns_rr_CAA::to_string() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + boost::lexical_cast<string>(get_ttl()) + " " + boost::lexical_cast<string>(int(get_flags())) + " " + get_tag()->to_string() + " " + util::tobase64(get_contents());
}

string dns_rr_CAA::to_string_no_ttl() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + boost::lexical_cast<string>(int(get_flags())) + " " + get_tag()->to_string() + " " + util::tobase64(get_contents());
}
