//
//  Copyright 2025 Andrew Haisley
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and 
//  associated documentation files (the “Software”), to deal in the Software without restriction, 
//  including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
//  and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, 
//  subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all copies or substantial 
//  portions of the Software.
//
//  THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT 
//  NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
//  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
//  WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
//  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
 
#pragma once

/**
 * automatically generated by rrgen.py at 02:39PM on November 03, 2025 do not edit by hand.
 */

#include <boost/lexical_cast.hpp>

#include "dns_rr.hpp"

namespace adns
{
    /**
     * DNS resource record type SOA (type number 6)
     */
    class dns_rr_SOA final : public dns_rr
    {
    public:

        /**
         * Constructor 
         */
        dns_rr_SOA();

        /**
         * Destructor 
         */
        virtual ~dns_rr_SOA();

        /**
         * make a copy 
         */
        virtual dns_rr *clone();

        /**
         * set methods
         */
        void set_mname(const std::shared_ptr<dns_name> &mname);
        void set_rname(const std::shared_ptr<dns_name> &rname);
        void set_serial(uint serial);
        void set_refresh(int refresh);
        void set_retry(int retry);
        void set_expire(int expire);
        void set_minimum(uint minimum);

        /**
         * get methods
         */
        const std::shared_ptr<dns_name> &get_mname() const;
        const std::shared_ptr<dns_name> &get_rname() const;
        uint get_serial() const;
        int get_refresh() const;
        int get_retry() const;
        int get_expire() const;
        uint get_minimum() const;

        /**
         * dump out for debug
         */
        virtual void dump() const;

        /**
         * turn into a string for logging/debug/comparison
         */
        virtual std::string to_string() const;

        /**
         * turn into a string for logging/debug/comparison with no TTL
         */
        virtual std::string to_string_no_ttl() const;

    protected:

        /**
         * serialize into a json object
         */
        virtual void json_serialize() const;

        /**
         * unserialize from a json object
         */
        virtual void json_unserialize();

    private:

        std::shared_ptr<dns_name> m_mname;
        std::shared_ptr<dns_name> m_rname;
        uint m_serial;
        int m_refresh;
        int m_retry;
        int m_expire;
        uint m_minimum;

    };
}
