//
//  Copyright 2025 Andrew Haisley
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and 
//  associated documentation files (the “Software”), to deal in the Software without restriction, 
//  including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
//  and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, 
//  subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all copies or substantial 
//  portions of the Software.
//
//  THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT 
//  NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
//  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
//  WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
//  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
 
/**
 * automatically generated by rrgen.py at 02:39PM on November 03, 2025 do not edit by hand.
 */

#include <boost/lexical_cast.hpp>

#include "types.hpp"
#include "util.hpp"
#include "buffer.hpp"
#include "dns_type_bitmap.hpp"
#include "dns_rr_TLSA.hpp"

using namespace adns;
using namespace std;

dns_rr_TLSA::dns_rr_TLSA() : dns_rr()
{
    set_type(dns_rr::T_TLSA_e);
}

dns_rr_TLSA::~dns_rr_TLSA()
{
}

dns_rr *dns_rr_TLSA::clone()
{
    return new dns_rr_TLSA(*this);
}

void dns_rr_TLSA::json_serialize() const
{
    dns_rr::json_serialize();
    set_json("certifcate_usage", int(get_certifcate_usage()));
    set_json("selector", int(get_selector()));
    set_json("matching_type", int(get_matching_type()));
    set_json("certificate_association", util::tohex(get_certificate_association()));

}

void dns_rr_TLSA::json_unserialize() 
{
    m_certifcate_usage = int((*m_json_object)["certifcate_usage"]);
    m_selector = int((*m_json_object)["selector"]);
    m_matching_type = int((*m_json_object)["matching_type"]);
    m_certificate_association = util::fromhex((*m_json_object)["certificate_association"]);

}

void dns_rr_TLSA::set_certifcate_usage(octet certifcate_usage)
{
    m_certifcate_usage = certifcate_usage;
}
void dns_rr_TLSA::set_selector(octet selector)
{
    m_selector = selector;
}
void dns_rr_TLSA::set_matching_type(octet matching_type)
{
    m_matching_type = matching_type;
}
void dns_rr_TLSA::set_certificate_association(const buffer &certificate_association)
{
    m_certificate_association = certificate_association;
}

octet dns_rr_TLSA::get_certifcate_usage() const
{
    return m_certifcate_usage;
}
octet dns_rr_TLSA::get_selector() const
{
    return m_selector;
}
octet dns_rr_TLSA::get_matching_type() const
{
    return m_matching_type;
}
const buffer &dns_rr_TLSA::get_certificate_association() const
{
    return m_certificate_association;
}


void dns_rr_TLSA::dump() const
{
    LOG(debug) << to_string();
}

string dns_rr_TLSA::to_string() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + boost::lexical_cast<string>(get_ttl()) + " " + boost::lexical_cast<string>(int(get_certifcate_usage())) + " " + boost::lexical_cast<string>(int(get_selector())) + " " + boost::lexical_cast<string>(int(get_matching_type())) + " " + util::tohex(get_certificate_association());
}

string dns_rr_TLSA::to_string_no_ttl() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + boost::lexical_cast<string>(int(get_certifcate_usage())) + " " + boost::lexical_cast<string>(int(get_selector())) + " " + boost::lexical_cast<string>(int(get_matching_type())) + " " + util::tohex(get_certificate_association());
}
