//
//  Copyright 2025 Andrew Haisley
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and 
//  associated documentation files (the “Software”), to deal in the Software without restriction, 
//  including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
//  and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, 
//  subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all copies or substantial 
//  portions of the Software.
//
//  THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT 
//  NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
//  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
//  WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
//  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
 
/**
 * automatically generated by rrgen.py at 02:39PM on November 03, 2025 do not edit by hand.
 */

#include <boost/lexical_cast.hpp>

#include "types.hpp"
#include "util.hpp"
#include "buffer.hpp"
#include "dns_type_bitmap.hpp"
#include "dns_rr_EUI64.hpp"

using namespace adns;
using namespace std;

dns_rr_EUI64::dns_rr_EUI64() : dns_rr()
{
    set_type(dns_rr::T_EUI64_e);
}

dns_rr_EUI64::~dns_rr_EUI64()
{
}

dns_rr *dns_rr_EUI64::clone()
{
    return new dns_rr_EUI64(*this);
}

void dns_rr_EUI64::json_serialize() const
{
    dns_rr::json_serialize();
    set_json("eui64", get_eui64().to_string());

}

void dns_rr_EUI64::json_unserialize() 
{
    m_eui64 = eui64((*m_json_object)["eui64"]);

}

void dns_rr_EUI64::set_eui64(const eui64 &eui64)
{
    m_eui64 = eui64;
}

const eui64 &dns_rr_EUI64::get_eui64() const
{
    return m_eui64;
}


void dns_rr_EUI64::dump() const
{
    LOG(debug) << to_string();
}

string dns_rr_EUI64::to_string() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + boost::lexical_cast<string>(get_ttl()) + " " + get_eui64().to_string();
}

string dns_rr_EUI64::to_string_no_ttl() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + get_eui64().to_string();
}
