// 
// Copyright 2025 Andrew Haisley
// 
// This program is free software: you can redistribute it and/or modify it under the terms 
// of the GNU General Public License as published by the Free Software Foundation, either 
// version 3 of the License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
// See the GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License along with this program. 
// If not, see https://www.gnu.org/licenses/.
// 
/**
 * automatically generated by rrgen.py at 05:05PM on January 30, 2024 do not edit by hand.
 */

#include <boost/lexical_cast.hpp>

#include "types.hpp"
#include "util.hpp"
#include "buffer.hpp"
#include "dns_type_bitmap.hpp"
#include "dns_rr_A.hpp"

using namespace adns;
using namespace std;

dns_rr_A::dns_rr_A() : dns_rr()
{
    set_type(dns_rr::T_A_e);
}

dns_rr_A::~dns_rr_A()
{
}

dns_rr *dns_rr_A::clone()
{
    return new dns_rr_A(*this);
}

void dns_rr_A::json_serialize() const
{
    dns_rr::json_serialize();
    set_json("ip4_addr", get_ip4_addr().to_string());

}

void dns_rr_A::json_unserialize() 
{
    m_ip4_addr = ip_address((*m_json_object)["ip4_addr"]);

}

void dns_rr_A::set_ip4_addr(const ip_address &ip4_addr)
{
    m_ip4_addr = ip4_addr;
}

const ip_address &dns_rr_A::get_ip4_addr() const
{
    return m_ip4_addr;
}


void dns_rr_A::dump() const
{
    LOG(debug) << to_string();
}

string dns_rr_A::to_string() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + boost::lexical_cast<string>(get_ttl()) + " " + get_ip4_addr().to_string();
}

string dns_rr_A::to_string_no_ttl() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + get_ip4_addr().to_string();
}
