// 
// Copyright 2025 Andrew Haisley
// 
// This program is free software: you can redistribute it and/or modify it under the terms 
// of the GNU General Public License as published by the Free Software Foundation, either 
// version 3 of the License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
// See the GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License along with this program. 
// If not, see https://www.gnu.org/licenses/.
// 
/**
 * automatically generated by rrgen.py at 05:05PM on January 30, 2024 do not edit by hand.
 */

#include <boost/lexical_cast.hpp>

#include "types.hpp"
#include "util.hpp"
#include "buffer.hpp"
#include "dns_type_bitmap.hpp"
#include "dns_rr_SRV.hpp"

using namespace adns;
using namespace std;

dns_rr_SRV::dns_rr_SRV() : dns_rr()
{
    set_type(dns_rr::T_SRV_e);
}

dns_rr_SRV::~dns_rr_SRV()
{
}

dns_rr *dns_rr_SRV::clone()
{
    return new dns_rr_SRV(*this);
}

void dns_rr_SRV::json_serialize() const
{
    dns_rr::json_serialize();
    set_json("priority", int(get_priority()));
    set_json("weight", int(get_weight()));
    set_json("port", int(get_port()));
    set_json("target", get_target()->to_string());

}

void dns_rr_SRV::json_unserialize() 
{
    m_priority = int((*m_json_object)["priority"]);
    m_weight = int((*m_json_object)["weight"]);
    m_port = int((*m_json_object)["port"]);
    m_target = make_shared<dns_name>((*m_json_object)["target"]);

}

void dns_rr_SRV::set_priority(unsigned short priority)
{
    m_priority = priority;
}
void dns_rr_SRV::set_weight(unsigned short weight)
{
    m_weight = weight;
}
void dns_rr_SRV::set_port(unsigned short port)
{
    m_port = port;
}
void dns_rr_SRV::set_target(const std::shared_ptr<dns_name> &target)
{
    m_target = target;
}

unsigned short dns_rr_SRV::get_priority() const
{
    return m_priority;
}
unsigned short dns_rr_SRV::get_weight() const
{
    return m_weight;
}
unsigned short dns_rr_SRV::get_port() const
{
    return m_port;
}
const std::shared_ptr<dns_name> &dns_rr_SRV::get_target() const
{
    return m_target;
}


void dns_rr_SRV::dump() const
{
    LOG(debug) << to_string();
}

string dns_rr_SRV::to_string() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + boost::lexical_cast<string>(get_ttl()) + " " + boost::lexical_cast<string>(get_priority()) + " " + boost::lexical_cast<string>(get_weight()) + " " + boost::lexical_cast<string>(get_port()) + " " + get_target()->to_string();
}

string dns_rr_SRV::to_string_no_ttl() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + boost::lexical_cast<string>(get_priority()) + " " + boost::lexical_cast<string>(get_weight()) + " " + boost::lexical_cast<string>(get_port()) + " " + get_target()->to_string();
}
