// 
// Copyright 2025 Andrew Haisley
// 
// This program is free software: you can redistribute it and/or modify it under the terms 
// of the GNU General Public License as published by the Free Software Foundation, either 
// version 3 of the License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
// See the GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License along with this program. 
// If not, see https://www.gnu.org/licenses/.
// 
/**
 * automatically generated by rrgen.py at 05:05PM on January 30, 2024 do not edit by hand.
 */

#include <boost/lexical_cast.hpp>

#include "types.hpp"
#include "util.hpp"
#include "buffer.hpp"
#include "dns_type_bitmap.hpp"
#include "dns_rr_CNAME.hpp"

using namespace adns;
using namespace std;

dns_rr_CNAME::dns_rr_CNAME() : dns_rr()
{
    set_type(dns_rr::T_CNAME_e);
}

dns_rr_CNAME::~dns_rr_CNAME()
{
}

dns_rr *dns_rr_CNAME::clone()
{
    return new dns_rr_CNAME(*this);
}

void dns_rr_CNAME::json_serialize() const
{
    dns_rr::json_serialize();
    set_json("cname", get_cname()->to_string());

}

void dns_rr_CNAME::json_unserialize() 
{
    m_cname = make_shared<dns_name>((*m_json_object)["cname"]);

}

void dns_rr_CNAME::set_cname(const std::shared_ptr<dns_name> &cname)
{
    m_cname = cname;
}

const std::shared_ptr<dns_name> &dns_rr_CNAME::get_cname() const
{
    return m_cname;
}


void dns_rr_CNAME::dump() const
{
    LOG(debug) << to_string();
}

string dns_rr_CNAME::to_string() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + boost::lexical_cast<string>(get_ttl()) + " " + get_cname()->to_string();
}

string dns_rr_CNAME::to_string_no_ttl() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + get_cname()->to_string();
}
