//
//  Copyright 2025 Andrew Haisley
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and 
//  associated documentation files (the “Software”), to deal in the Software without restriction, 
//  including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
//  and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, 
//  subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all copies or substantial 
//  portions of the Software.
//
//  THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT 
//  NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
//  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
//  WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
//  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
 
/**
 * automatically generated by rrgen.py at 11:28AM on November 02, 2025 do not edit by hand.
 */

#include <boost/lexical_cast.hpp>

#include "types.hpp"
#include "util.hpp"
#include "buffer.hpp"
#include "dns_type_bitmap.hpp"
#include "dns_rr_A.hpp"

using namespace adns;
using namespace std;

dns_rr_A::dns_rr_A() : dns_rr()
{
    set_type(dns_rr::T_A_e);
}

dns_rr_A::~dns_rr_A()
{
}

dns_rr *dns_rr_A::clone()
{
    return new dns_rr_A(*this);
}

void dns_rr_A::json_serialize() const
{
    dns_rr::json_serialize();
    set_json("ip4_addr", get_ip4_addr().to_string());

}

void dns_rr_A::json_unserialize() 
{
    m_ip4_addr = ip_address((*m_json_object)["ip4_addr"]);

}

void dns_rr_A::set_ip4_addr(const ip_address &ip4_addr)
{
    m_ip4_addr = ip4_addr;
}

const ip_address &dns_rr_A::get_ip4_addr() const
{
    return m_ip4_addr;
}


void dns_rr_A::dump() const
{
    LOG(debug) << to_string();
}

string dns_rr_A::to_string() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + boost::lexical_cast<string>(get_ttl()) + " " + get_ip4_addr().to_string();
}

string dns_rr_A::to_string_no_ttl() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + get_ip4_addr().to_string();
}
