//
//  Copyright 2025 Andrew Haisley
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and 
//  associated documentation files (the “Software”), to deal in the Software without restriction, 
//  including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
//  and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, 
//  subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all copies or substantial 
//  portions of the Software.
//
//  THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT 
//  NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
//  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
//  WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
//  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
 
/**
 * automatically generated by rrgen.py at 11:28AM on November 02, 2025 do not edit by hand.
 */

#include <boost/lexical_cast.hpp>

#include "types.hpp"
#include "util.hpp"
#include "buffer.hpp"
#include "dns_type_bitmap.hpp"
#include "dns_rr_AFSDB.hpp"

using namespace adns;
using namespace std;

dns_rr_AFSDB::dns_rr_AFSDB() : dns_rr()
{
    set_type(dns_rr::T_AFSDB_e);
}

dns_rr_AFSDB::~dns_rr_AFSDB()
{
}

dns_rr *dns_rr_AFSDB::clone()
{
    return new dns_rr_AFSDB(*this);
}

void dns_rr_AFSDB::json_serialize() const
{
    dns_rr::json_serialize();
    set_json("subtype", int(get_subtype()));
    set_json("hostname", get_hostname()->to_string());

}

void dns_rr_AFSDB::json_unserialize() 
{
    m_subtype = int((*m_json_object)["subtype"]);
    m_hostname = make_shared<dns_name>((*m_json_object)["hostname"]);

}

void dns_rr_AFSDB::set_subtype(unsigned short subtype)
{
    m_subtype = subtype;
}
void dns_rr_AFSDB::set_hostname(const std::shared_ptr<dns_name> &hostname)
{
    m_hostname = hostname;
}

unsigned short dns_rr_AFSDB::get_subtype() const
{
    return m_subtype;
}
const std::shared_ptr<dns_name> &dns_rr_AFSDB::get_hostname() const
{
    return m_hostname;
}


void dns_rr_AFSDB::dump() const
{
    LOG(debug) << to_string();
}

string dns_rr_AFSDB::to_string() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + boost::lexical_cast<string>(get_ttl()) + " " + boost::lexical_cast<string>(get_subtype()) + " " + get_hostname()->to_string();
}

string dns_rr_AFSDB::to_string_no_ttl() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + boost::lexical_cast<string>(get_subtype()) + " " + get_hostname()->to_string();
}
