//
//  Copyright 2025 Andrew Haisley
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and 
//  associated documentation files (the “Software”), to deal in the Software without restriction, 
//  including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
//  and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, 
//  subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all copies or substantial 
//  portions of the Software.
//
//  THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT 
//  NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
//  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
//  WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
//  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
 
/**
 * automatically generated by rrgen.py at 05:05PM on January 30, 2024 do not edit by hand.
 */

#include <boost/lexical_cast.hpp>

#include "types.hpp"
#include "util.hpp"
#include "buffer.hpp"
#include "dns_type_bitmap.hpp"
#include "dns_rr_CERT.hpp"

using namespace adns;
using namespace std;

dns_rr_CERT::dns_rr_CERT() : dns_rr()
{
    set_type(dns_rr::T_CERT_e);
}

dns_rr_CERT::~dns_rr_CERT()
{
}

dns_rr *dns_rr_CERT::clone()
{
    return new dns_rr_CERT(*this);
}

void dns_rr_CERT::json_serialize() const
{
    dns_rr::json_serialize();
    set_json("certificate_type", int(get_certificate_type()));
    set_json("key_tag", int(get_key_tag()));
    set_json("algorithm", int(get_algorithm()));
    set_json("certificate", util::tobase64(get_certificate()));

}

void dns_rr_CERT::json_unserialize() 
{
    m_certificate_type = int((*m_json_object)["certificate_type"]);
    m_key_tag = int((*m_json_object)["key_tag"]);
    m_algorithm = int((*m_json_object)["algorithm"]);
    m_certificate = util::frombase64((*m_json_object)["certificate"]);

}

void dns_rr_CERT::set_certificate_type(unsigned short certificate_type)
{
    m_certificate_type = certificate_type;
}
void dns_rr_CERT::set_key_tag(unsigned short key_tag)
{
    m_key_tag = key_tag;
}
void dns_rr_CERT::set_algorithm(octet algorithm)
{
    m_algorithm = algorithm;
}
void dns_rr_CERT::set_certificate(const buffer &certificate)
{
    m_certificate = certificate;
}

unsigned short dns_rr_CERT::get_certificate_type() const
{
    return m_certificate_type;
}
unsigned short dns_rr_CERT::get_key_tag() const
{
    return m_key_tag;
}
octet dns_rr_CERT::get_algorithm() const
{
    return m_algorithm;
}
const buffer &dns_rr_CERT::get_certificate() const
{
    return m_certificate;
}


void dns_rr_CERT::dump() const
{
    LOG(debug) << to_string();
}

string dns_rr_CERT::to_string() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + boost::lexical_cast<string>(get_ttl()) + " " + boost::lexical_cast<string>(get_certificate_type()) + " " + boost::lexical_cast<string>(get_key_tag()) + " " + boost::lexical_cast<string>(int(get_algorithm())) + " " + util::tobase64(get_certificate());
}

string dns_rr_CERT::to_string_no_ttl() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + boost::lexical_cast<string>(get_certificate_type()) + " " + boost::lexical_cast<string>(get_key_tag()) + " " + boost::lexical_cast<string>(int(get_algorithm())) + " " + util::tobase64(get_certificate());
}
