//
//  Copyright 2025 Andrew Haisley
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and 
//  associated documentation files (the “Software”), to deal in the Software without restriction, 
//  including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
//  and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, 
//  subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all copies or substantial 
//  portions of the Software.
//
//  THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT 
//  NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
//  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
//  WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
//  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
 
/**
 * automatically generated by rrgen.py at 05:05PM on January 30, 2024 do not edit by hand.
 */

#include <boost/lexical_cast.hpp>

#include "types.hpp"
#include "util.hpp"
#include "buffer.hpp"
#include "dns_type_bitmap.hpp"
#include "dns_rr_SSHFP.hpp"

using namespace adns;
using namespace std;

dns_rr_SSHFP::dns_rr_SSHFP() : dns_rr()
{
    set_type(dns_rr::T_SSHFP_e);
}

dns_rr_SSHFP::~dns_rr_SSHFP()
{
}

dns_rr *dns_rr_SSHFP::clone()
{
    return new dns_rr_SSHFP(*this);
}

void dns_rr_SSHFP::json_serialize() const
{
    dns_rr::json_serialize();
    set_json("algorithm", int(get_algorithm()));
    set_json("fp_type", int(get_fp_type()));
    set_json("fingerprint", util::tohex(get_fingerprint()));

}

void dns_rr_SSHFP::json_unserialize() 
{
    m_algorithm = int((*m_json_object)["algorithm"]);
    m_fp_type = int((*m_json_object)["fp_type"]);
    m_fingerprint = util::fromhex((*m_json_object)["fingerprint"]);

}

void dns_rr_SSHFP::set_algorithm(octet algorithm)
{
    m_algorithm = algorithm;
}
void dns_rr_SSHFP::set_fp_type(octet fp_type)
{
    m_fp_type = fp_type;
}
void dns_rr_SSHFP::set_fingerprint(const buffer &fingerprint)
{
    m_fingerprint = fingerprint;
}

octet dns_rr_SSHFP::get_algorithm() const
{
    return m_algorithm;
}
octet dns_rr_SSHFP::get_fp_type() const
{
    return m_fp_type;
}
const buffer &dns_rr_SSHFP::get_fingerprint() const
{
    return m_fingerprint;
}


void dns_rr_SSHFP::dump() const
{
    LOG(debug) << to_string();
}

string dns_rr_SSHFP::to_string() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + boost::lexical_cast<string>(get_ttl()) + " " + boost::lexical_cast<string>(int(get_algorithm())) + " " + boost::lexical_cast<string>(int(get_fp_type())) + " " + util::tohex(get_fingerprint());
}

string dns_rr_SSHFP::to_string_no_ttl() const
{
    return (get_name() ? get_name()->to_string() : string("")) + " " + dns_rr::type_to_string(get_type()) + " " + boost::lexical_cast<string>(int(get_algorithm())) + " " + boost::lexical_cast<string>(int(get_fp_type())) + " " + util::tohex(get_fingerprint());
}
