// 
// Copyright 2025 Andrew Haisley
// 
// This program is free software: you can redistribute it and/or modify it under the terms 
// of the GNU General Public License as published by the Free Software Foundation, either 
// version 3 of the License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
// See the GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License along with this program. 
// If not, see https://www.gnu.org/licenses/.
// 
/**
 * autogenerated by dbgen.py at 11:00AM on October 26, 2025, do not hand edit
 */

#include <boost/uuid/uuid_generators.hpp>

#include "row_schema_version.hpp"

using namespace adns;
using namespace db;
using namespace std;

mutex row_schema_version::o_lock;
vector<column> row_schema_version::o_columns;
atomic<bool> row_schema_version::o_initialised(false);
column row_schema_version::o_primary_key;
vector<foreign_key> row_schema_version::o_foreign_keys;

static row_schema_version instance;

static shared_ptr<row_schema_version> convert_row_type(row *r)
{
    return shared_ptr<row_schema_version>(static_cast<row_schema_version*>(r));
}

static vector<shared_ptr<row_schema_version>> convert_row_type(vector<row *> vr)
{
    vector<shared_ptr<row_schema_version>> res(vr.size());
    for (size_t i = 0; i < vr.size(); i++)
    {
        res[i] = shared_ptr<row_schema_version>(static_cast<row_schema_version*>(vr[i]));
    }
    return res;
}

    
row_schema_version::row_schema_version()
{
    
}

row_schema_version::~row_schema_version()
{
}

vector<shared_ptr<row_schema_version>> row_schema_version::get_rows(connection &conn)
{
    return convert_row_type(instance.fetch_rows(conn));
}

string row_schema_version::get_table_name() const
{
    return "schema_version";
}

table::table_t row_schema_version::get_table_id() const
{
    return table::schema_version_e;
}

row *row_schema_version::create_instance() const
{
    return new row_schema_version();
}

void row_schema_version::set_column_value(const column &c, int value)
{
    (void)value;
    THROW(row_exception, "no columns of type int found", c.get_position());
}

void row_schema_version::set_column_value(const column &c, bool value)
{
    (void)value;
    THROW(row_exception, "no columns of type bool found", c.get_position());
}

void row_schema_version::set_column_value(const column &c, uint value)
{
    (void)value;
    THROW(row_exception, "no columns of type uint found", c.get_position());
}

void row_schema_version::set_column_value(const column &c, octet value)
{
    (void)value;
    THROW(row_exception, "no columns of type octet found", c.get_position());
}

void row_schema_version::set_column_value(const column &c, uuid value)
{
    switch (c.get_position())
    {
    case 1:
        m_schema_version_id = value;
        break;
    default:
        THROW(row_exception, "no columns of type uuid found at position", c.get_position());
    }
}

void row_schema_version::set_column_value(const column &c, const string &value)
{
    switch (c.get_position())
    {
    case 2:
        m_version_string = value;
        break;
    default:
        THROW(row_exception, "no columns of type string found at position", c.get_position());
    }
}

void row_schema_version::set_column_value(const column &c, const datetime &value)
{
    (void)value;
    THROW(row_exception, "no columns of type datetime found", c.get_position());
}

void row_schema_version::set_column_value(const column &c, const buffer &value)
{
    (void)value;
    THROW(row_exception, "no columns of type buffer found", c.get_position());
}

void row_schema_version::set_column_value(const column &c, nullable<int> value)
{
    (void)value;
    THROW(row_exception, "no columns of type int found", c.get_position());
}

void row_schema_version::set_column_value(const column &c, nullable<bool> value)
{
    (void)value;
    THROW(row_exception, "no columns of type bool found", c.get_position());
}

void row_schema_version::set_column_value(const column &c, nullable<uint> value)
{
    (void)value;
    THROW(row_exception, "no columns of type uint found", c.get_position());
}

void row_schema_version::set_column_value(const column &c, nullable<octet> value)
{
    (void)value;
    THROW(row_exception, "no columns of type octet found", c.get_position());
}

void row_schema_version::set_column_value(const column &c, nullable<uuid> value)
{
    (void)value;
    THROW(row_exception, "no columns of type uuid found", c.get_position());
}

void row_schema_version::set_column_value(const column &c, const nullable<string> &value)
{
    (void)value;
    THROW(row_exception, "no columns of type string found", c.get_position());
}

void row_schema_version::set_column_value(const column &c, const nullable<datetime> &value)
{
    (void)value;
    THROW(row_exception, "no columns of type datetime found", c.get_position());
}

void row_schema_version::set_column_value(const column &c, const nullable<buffer> &value)
{
    (void)value;
    THROW(row_exception, "no columns of type buffer found", c.get_position());
}

int row_schema_version::get_int_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type int found", c.get_name(), c.get_position());
}

bool row_schema_version::get_bool_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type bool found", c.get_name(), c.get_position());
}

uint row_schema_version::get_uint_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type uint found", c.get_name(), c.get_position());
}

octet row_schema_version::get_octet_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type octet found", c.get_name(), c.get_position());
}

uuid row_schema_version::get_uuid_column_value(const column &c) const
{
    switch (c.get_position())
    {
    case 1:
        return m_schema_version_id;
    default:
        THROW(row_exception, "no columns of type uuid found at position", c.get_name(), c.get_position());
    }
}

const string &row_schema_version::get_string_column_value(const column &c) const
{
    switch (c.get_position())
    {
    case 2:
        return m_version_string;
    default:
        THROW(row_exception, "no columns of type string found at position", c.get_name(), c.get_position());
    }
}

const datetime &row_schema_version::get_datetime_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type datetime found", c.get_name(), c.get_position());
}

const buffer &row_schema_version::get_buffer_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type buffer found", c.get_name(), c.get_position());
}

nullable<int> row_schema_version::get_nullable_int_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type int found", c.get_name(), c.get_position());
}

nullable<bool> row_schema_version::get_nullable_bool_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type bool found", c.get_name(), c.get_position());
}

nullable<uint> row_schema_version::get_nullable_uint_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type uint found", c.get_name(), c.get_position());
}

nullable<octet> row_schema_version::get_nullable_octet_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type octet found", c.get_name(), c.get_position());
}

nullable<uuid> row_schema_version::get_nullable_uuid_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type uuid found", c.get_name(), c.get_position());
}

const nullable<string> &row_schema_version::get_nullable_string_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type string found", c.get_name(), c.get_position());
}

const nullable<datetime> &row_schema_version::get_nullable_datetime_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type datetime found", c.get_name(), c.get_position());
}

const nullable<buffer> &row_schema_version::get_nullable_buffer_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type buffer found", c.get_name(), c.get_position());
}

const vector<column> &row_schema_version::get_columns() const
{
    init_static();
    return o_columns;
}

const vector<foreign_key> &row_schema_version::get_foreign_keys() const
{
    init_static();
    return o_foreign_keys;
}

const column &row_schema_version::get_primary_key() const
{
    init_static();
    return o_primary_key;
}

uuid row_schema_version::get_primary_key_value() const
{
    return get_uuid_column_value(get_primary_key());
}

void row_schema_version::init_static()
{
    if (!o_initialised)
    {
        lock_guard<mutex> guard(o_lock);
        if (!o_initialised)
        {
            o_columns.push_back(column(column::uuid_e, "schema_version_id", 1, false));
            o_primary_key = column(column::uuid_e, "schema_version_id", 1, false);
            o_columns.push_back(column(column::string_e, "version_string", 2, false));
            
            o_initialised = true;
        }
    }
}

shared_ptr<row_schema_version> row_schema_version::get_by_schema_version_id(connection &c, uuid schema_version_id)
{
    init_static();
    return convert_row_type(instance.fetch_row(c, o_columns[0], schema_version_id));
}



void row_schema_version::delete_by_schema_version_id(connection &c, uuid schema_version_id)
{
    init_static();
    instance.delete_rows(c, o_columns[0], schema_version_id);
}



uuid row_schema_version::get_schema_version_id() const
{
    return m_schema_version_id;
}

string row_schema_version::get_version_string() const
{
    return m_version_string;
}



void row_schema_version::set_schema_version_id(uuid v)
{
    m_schema_version_id = v;
}

void row_schema_version::set_version_string(string v)
{
    m_version_string = v;
}


