// 
// Copyright 2025 Andrew Haisley
// 
// This program is free software: you can redistribute it and/or modify it under the terms 
// of the GNU General Public License as published by the Free Software Foundation, either 
// version 3 of the License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
// See the GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License along with this program. 
// If not, see https://www.gnu.org/licenses/.
// 
/**
 * autogenerated by dbgen.py at 03:09PM on March 22, 2025, do not hand edit
 */

#include <boost/uuid/uuid_generators.hpp>

#include "row_rr_csync.hpp"

using namespace adns;
using namespace db;
using namespace std;

mutex row_rr_csync::o_lock;
vector<column> row_rr_csync::o_columns;
atomic<bool> row_rr_csync::o_initialised(false);
column row_rr_csync::o_primary_key;
vector<foreign_key> row_rr_csync::o_foreign_keys;

static row_rr_csync instance;

static shared_ptr<row_rr_csync> convert_row_type(row *r)
{
    return shared_ptr<row_rr_csync>(static_cast<row_rr_csync*>(r));
}

static vector<shared_ptr<row_rr_csync>> convert_row_type(vector<row *> vr)
{
    vector<shared_ptr<row_rr_csync>> res(vr.size());
    for (size_t i = 0; i < vr.size(); i++)
    {
        res[i] = shared_ptr<row_rr_csync>(static_cast<row_rr_csync*>(vr[i]));
    }
    return res;
}

    
row_rr_csync::row_rr_csync()
{
    m_flags = 0;
    m_soa_serial = 0;
    m_ttl = 0;
}

row_rr_csync::~row_rr_csync()
{
}

vector<shared_ptr<row_rr_csync>> row_rr_csync::get_rows(connection &conn)
{
    return convert_row_type(instance.fetch_rows(conn));
}

string row_rr_csync::get_table_name() const
{
    return "rr_csync";
}

table::table_t row_rr_csync::get_table_id() const
{
    return table::rr_csync_e;
}

row *row_rr_csync::create_instance() const
{
    return new row_rr_csync();
}

void row_rr_csync::set_column_value(const column &c, int value)
{
    (void)value;
    THROW(row_exception, "no columns of type int found", c.get_position());
}

void row_rr_csync::set_column_value(const column &c, bool value)
{
    (void)value;
    THROW(row_exception, "no columns of type bool found", c.get_position());
}

void row_rr_csync::set_column_value(const column &c, uint value)
{
    switch (c.get_position())
    {
    case 1:
        m_flags = value;
        break;
    case 4:
        m_soa_serial = value;
        break;
    case 5:
        m_ttl = value;
        break;
    default:
        THROW(row_exception, "no columns of type uint found at position", c.get_position());
    }
}

void row_rr_csync::set_column_value(const column &c, octet value)
{
    (void)value;
    THROW(row_exception, "no columns of type octet found", c.get_position());
}

void row_rr_csync::set_column_value(const column &c, uuid value)
{
    switch (c.get_position())
    {
    case 3:
        m_rr_csync_id = value;
        break;
    case 7:
        m_zone_id = value;
        break;
    default:
        THROW(row_exception, "no columns of type uuid found at position", c.get_position());
    }
}

void row_rr_csync::set_column_value(const column &c, const string &value)
{
    switch (c.get_position())
    {
    case 2:
        m_name = value;
        break;
    case 6:
        m_type_bitmap = value;
        break;
    default:
        THROW(row_exception, "no columns of type string found at position", c.get_position());
    }
}

void row_rr_csync::set_column_value(const column &c, const datetime &value)
{
    (void)value;
    THROW(row_exception, "no columns of type datetime found", c.get_position());
}

void row_rr_csync::set_column_value(const column &c, const buffer &value)
{
    (void)value;
    THROW(row_exception, "no columns of type buffer found", c.get_position());
}

void row_rr_csync::set_column_value(const column &c, nullable<int> value)
{
    (void)value;
    THROW(row_exception, "no columns of type int found", c.get_position());
}

void row_rr_csync::set_column_value(const column &c, nullable<bool> value)
{
    (void)value;
    THROW(row_exception, "no columns of type bool found", c.get_position());
}

void row_rr_csync::set_column_value(const column &c, nullable<uint> value)
{
    (void)value;
    THROW(row_exception, "no columns of type uint found", c.get_position());
}

void row_rr_csync::set_column_value(const column &c, nullable<octet> value)
{
    (void)value;
    THROW(row_exception, "no columns of type octet found", c.get_position());
}

void row_rr_csync::set_column_value(const column &c, nullable<uuid> value)
{
    (void)value;
    THROW(row_exception, "no columns of type uuid found", c.get_position());
}

void row_rr_csync::set_column_value(const column &c, const nullable<string> &value)
{
    (void)value;
    THROW(row_exception, "no columns of type string found", c.get_position());
}

void row_rr_csync::set_column_value(const column &c, const nullable<datetime> &value)
{
    (void)value;
    THROW(row_exception, "no columns of type datetime found", c.get_position());
}

void row_rr_csync::set_column_value(const column &c, const nullable<buffer> &value)
{
    (void)value;
    THROW(row_exception, "no columns of type buffer found", c.get_position());
}

int row_rr_csync::get_int_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type int found", c.get_name(), c.get_position());
}

bool row_rr_csync::get_bool_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type bool found", c.get_name(), c.get_position());
}

uint row_rr_csync::get_uint_column_value(const column &c) const
{
    switch (c.get_position())
    {
    case 1:
        return m_flags;
    case 4:
        return m_soa_serial;
    case 5:
        return m_ttl;
    default:
        THROW(row_exception, "no columns of type uint found at position", c.get_name(), c.get_position());
    }
}

octet row_rr_csync::get_octet_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type octet found", c.get_name(), c.get_position());
}

uuid row_rr_csync::get_uuid_column_value(const column &c) const
{
    switch (c.get_position())
    {
    case 3:
        return m_rr_csync_id;
    case 7:
        return m_zone_id;
    default:
        THROW(row_exception, "no columns of type uuid found at position", c.get_name(), c.get_position());
    }
}

const string &row_rr_csync::get_string_column_value(const column &c) const
{
    switch (c.get_position())
    {
    case 2:
        return m_name;
    case 6:
        return m_type_bitmap;
    default:
        THROW(row_exception, "no columns of type string found at position", c.get_name(), c.get_position());
    }
}

const datetime &row_rr_csync::get_datetime_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type datetime found", c.get_name(), c.get_position());
}

const buffer &row_rr_csync::get_buffer_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type buffer found", c.get_name(), c.get_position());
}

nullable<int> row_rr_csync::get_nullable_int_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type int found", c.get_name(), c.get_position());
}

nullable<bool> row_rr_csync::get_nullable_bool_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type bool found", c.get_name(), c.get_position());
}

nullable<uint> row_rr_csync::get_nullable_uint_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type uint found", c.get_name(), c.get_position());
}

nullable<octet> row_rr_csync::get_nullable_octet_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type octet found", c.get_name(), c.get_position());
}

nullable<uuid> row_rr_csync::get_nullable_uuid_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type uuid found", c.get_name(), c.get_position());
}

const nullable<string> &row_rr_csync::get_nullable_string_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type string found", c.get_name(), c.get_position());
}

const nullable<datetime> &row_rr_csync::get_nullable_datetime_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type datetime found", c.get_name(), c.get_position());
}

const nullable<buffer> &row_rr_csync::get_nullable_buffer_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type buffer found", c.get_name(), c.get_position());
}

const vector<column> &row_rr_csync::get_columns() const
{
    init_static();
    return o_columns;
}

const vector<foreign_key> &row_rr_csync::get_foreign_keys() const
{
    init_static();
    return o_foreign_keys;
}

const column &row_rr_csync::get_primary_key() const
{
    init_static();
    return o_primary_key;
}

uuid row_rr_csync::get_primary_key_value() const
{
    return get_uuid_column_value(get_primary_key());
}

void row_rr_csync::init_static()
{
    if (!o_initialised)
    {
        lock_guard<mutex> guard(o_lock);
        if (!o_initialised)
        {
            o_columns.push_back(column(column::uint_e, "flags", 1, false));
            o_columns.push_back(column(column::string_e, "name", 2, false));
            o_columns.push_back(column(column::uuid_e, "rr_csync_id", 3, false));
            o_primary_key = column(column::uuid_e, "rr_csync_id", 3, false);
            o_columns.push_back(column(column::uint_e, "soa_serial", 4, false));
            o_columns.push_back(column(column::uint_e, "ttl", 5, false));
            o_columns.push_back(column(column::string_e, "type_bitmap", 6, false));
            o_columns.push_back(column(column::uuid_e, "zone_id", 7, false));
            
            o_initialised = true;
        }
    }
}

shared_ptr<row_rr_csync> row_rr_csync::get_by_rr_csync_id(connection &c, uuid rr_csync_id)
{
    init_static();
    return convert_row_type(instance.fetch_row(c, o_columns[2], rr_csync_id));
}

vector<shared_ptr<row_rr_csync>> row_rr_csync::get_by_zone_id(connection &c, uuid zone_id)
{
    init_static();
    return convert_row_type(instance.fetch_rows(c, o_columns[6], zone_id));
}



void row_rr_csync::delete_by_rr_csync_id(connection &c, uuid rr_csync_id)
{
    init_static();
    instance.delete_rows(c, o_columns[2], rr_csync_id);
}

void row_rr_csync::delete_by_zone_id(connection &c, uuid zone_id)
{
    init_static();
    instance.delete_rows(c, o_columns[6], zone_id);
}



uint row_rr_csync::get_flags() const
{
    return m_flags;
}

string row_rr_csync::get_name() const
{
    return m_name;
}

uuid row_rr_csync::get_rr_csync_id() const
{
    return m_rr_csync_id;
}

uint row_rr_csync::get_soa_serial() const
{
    return m_soa_serial;
}

uint row_rr_csync::get_ttl() const
{
    return m_ttl;
}

string row_rr_csync::get_type_bitmap() const
{
    return m_type_bitmap;
}

uuid row_rr_csync::get_zone_id() const
{
    return m_zone_id;
}



void row_rr_csync::set_flags(uint v)
{
    m_flags = v;
}

void row_rr_csync::set_name(string v)
{
    m_name = v;
}

void row_rr_csync::set_rr_csync_id(uuid v)
{
    m_rr_csync_id = v;
}

void row_rr_csync::set_soa_serial(uint v)
{
    m_soa_serial = v;
}

void row_rr_csync::set_ttl(uint v)
{
    m_ttl = v;
}

void row_rr_csync::set_type_bitmap(string v)
{
    m_type_bitmap = v;
}

void row_rr_csync::set_zone_id(uuid v)
{
    m_zone_id = v;
}


