// 
// Copyright 2025 Andrew Haisley
// 
// This program is free software: you can redistribute it and/or modify it under the terms 
// of the GNU General Public License as published by the Free Software Foundation, either 
// version 3 of the License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
// See the GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License along with this program. 
// If not, see https://www.gnu.org/licenses/.
// 
/**
 * autogenerated by dbgen.py at 11:28AM on November 02, 2025, do not hand edit
 */

#include <boost/uuid/uuid_generators.hpp>

#include "row_root_server.hpp"

using namespace adns;
using namespace db;
using namespace std;

mutex row_root_server::o_lock;
vector<column> row_root_server::o_columns;
atomic<bool> row_root_server::o_initialised(false);
column row_root_server::o_primary_key;
vector<foreign_key> row_root_server::o_foreign_keys;

static row_root_server instance;

static shared_ptr<row_root_server> convert_row_type(row *r)
{
    return shared_ptr<row_root_server>(static_cast<row_root_server*>(r));
}

static vector<shared_ptr<row_root_server>> convert_row_type(vector<row *> vr)
{
    vector<shared_ptr<row_root_server>> res(vr.size());
    for (size_t i = 0; i < vr.size(); i++)
    {
        res[i] = shared_ptr<row_root_server>(static_cast<row_root_server*>(vr[i]));
    }
    return res;
}

    
row_root_server::row_root_server()
{
    m_addr_ttl = 0;
    m_ns_ttl = 0;
}

row_root_server::~row_root_server()
{
}

vector<shared_ptr<row_root_server>> row_root_server::get_rows(connection &conn)
{
    return convert_row_type(instance.fetch_rows(conn));
}

string row_root_server::get_table_name() const
{
    return "root_server";
}

table::table_t row_root_server::get_table_id() const
{
    return table::root_server_e;
}

row *row_root_server::create_instance() const
{
    return new row_root_server();
}

void row_root_server::set_column_value(const column &c, int value)
{
    (void)value;
    THROW(row_exception, "no columns of type int found", c.get_position());
}

void row_root_server::set_column_value(const column &c, bool value)
{
    (void)value;
    THROW(row_exception, "no columns of type bool found", c.get_position());
}

void row_root_server::set_column_value(const column &c, uint value)
{
    switch (c.get_position())
    {
    case 1:
        m_addr_ttl = value;
        break;
    case 5:
        m_ns_ttl = value;
        break;
    default:
        THROW(row_exception, "no columns of type uint found at position", c.get_position());
    }
}

void row_root_server::set_column_value(const column &c, octet value)
{
    (void)value;
    THROW(row_exception, "no columns of type octet found", c.get_position());
}

void row_root_server::set_column_value(const column &c, uuid value)
{
    switch (c.get_position())
    {
    case 6:
        m_root_server_id = value;
        break;
    default:
        THROW(row_exception, "no columns of type uuid found at position", c.get_position());
    }
}

void row_root_server::set_column_value(const column &c, const string &value)
{
    switch (c.get_position())
    {
    case 2:
        m_ip_address = value;
        break;
    case 4:
        m_name = value;
        break;
    default:
        THROW(row_exception, "no columns of type string found at position", c.get_position());
    }
}

void row_root_server::set_column_value(const column &c, const datetime &value)
{
    switch (c.get_position())
    {
    case 3:
        m_last_contact_date_time = value;
        break;
    default:
        THROW(row_exception, "no columns of type datetime found at position", c.get_position());
    }
}

void row_root_server::set_column_value(const column &c, const buffer &value)
{
    (void)value;
    THROW(row_exception, "no columns of type buffer found", c.get_position());
}

void row_root_server::set_column_value(const column &c, nullable<int> value)
{
    (void)value;
    THROW(row_exception, "no columns of type int found", c.get_position());
}

void row_root_server::set_column_value(const column &c, nullable<bool> value)
{
    (void)value;
    THROW(row_exception, "no columns of type bool found", c.get_position());
}

void row_root_server::set_column_value(const column &c, nullable<uint> value)
{
    (void)value;
    THROW(row_exception, "no columns of type uint found", c.get_position());
}

void row_root_server::set_column_value(const column &c, nullable<octet> value)
{
    (void)value;
    THROW(row_exception, "no columns of type octet found", c.get_position());
}

void row_root_server::set_column_value(const column &c, nullable<uuid> value)
{
    (void)value;
    THROW(row_exception, "no columns of type uuid found", c.get_position());
}

void row_root_server::set_column_value(const column &c, const nullable<string> &value)
{
    (void)value;
    THROW(row_exception, "no columns of type string found", c.get_position());
}

void row_root_server::set_column_value(const column &c, const nullable<datetime> &value)
{
    (void)value;
    THROW(row_exception, "no columns of type datetime found", c.get_position());
}

void row_root_server::set_column_value(const column &c, const nullable<buffer> &value)
{
    (void)value;
    THROW(row_exception, "no columns of type buffer found", c.get_position());
}

int row_root_server::get_int_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type int found", c.get_name(), c.get_position());
}

bool row_root_server::get_bool_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type bool found", c.get_name(), c.get_position());
}

uint row_root_server::get_uint_column_value(const column &c) const
{
    switch (c.get_position())
    {
    case 1:
        return m_addr_ttl;
    case 5:
        return m_ns_ttl;
    default:
        THROW(row_exception, "no columns of type uint found at position", c.get_name(), c.get_position());
    }
}

octet row_root_server::get_octet_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type octet found", c.get_name(), c.get_position());
}

uuid row_root_server::get_uuid_column_value(const column &c) const
{
    switch (c.get_position())
    {
    case 6:
        return m_root_server_id;
    default:
        THROW(row_exception, "no columns of type uuid found at position", c.get_name(), c.get_position());
    }
}

const string &row_root_server::get_string_column_value(const column &c) const
{
    switch (c.get_position())
    {
    case 2:
        return m_ip_address;
    case 4:
        return m_name;
    default:
        THROW(row_exception, "no columns of type string found at position", c.get_name(), c.get_position());
    }
}

const datetime &row_root_server::get_datetime_column_value(const column &c) const
{
    switch (c.get_position())
    {
    case 3:
        return m_last_contact_date_time;
    default:
        THROW(row_exception, "no columns of type datetime found at position", c.get_name(), c.get_position());
    }
}

const buffer &row_root_server::get_buffer_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type buffer found", c.get_name(), c.get_position());
}

nullable<int> row_root_server::get_nullable_int_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type int found", c.get_name(), c.get_position());
}

nullable<bool> row_root_server::get_nullable_bool_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type bool found", c.get_name(), c.get_position());
}

nullable<uint> row_root_server::get_nullable_uint_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type uint found", c.get_name(), c.get_position());
}

nullable<octet> row_root_server::get_nullable_octet_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type octet found", c.get_name(), c.get_position());
}

nullable<uuid> row_root_server::get_nullable_uuid_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type uuid found", c.get_name(), c.get_position());
}

const nullable<string> &row_root_server::get_nullable_string_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type string found", c.get_name(), c.get_position());
}

const nullable<datetime> &row_root_server::get_nullable_datetime_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type datetime found", c.get_name(), c.get_position());
}

const nullable<buffer> &row_root_server::get_nullable_buffer_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type buffer found", c.get_name(), c.get_position());
}

const vector<column> &row_root_server::get_columns() const
{
    init_static();
    return o_columns;
}

const vector<foreign_key> &row_root_server::get_foreign_keys() const
{
    init_static();
    return o_foreign_keys;
}

const column &row_root_server::get_primary_key() const
{
    init_static();
    return o_primary_key;
}

uuid row_root_server::get_primary_key_value() const
{
    return get_uuid_column_value(get_primary_key());
}

void row_root_server::init_static()
{
    if (!o_initialised)
    {
        lock_guard<mutex> guard(o_lock);
        if (!o_initialised)
        {
            o_columns.push_back(column(column::uint_e, "addr_ttl", 1, false));
            o_columns.push_back(column(column::string_e, "ip_address", 2, false));
            o_columns.push_back(column(column::datetime_e, "last_contact_date_time", 3, false));
            o_columns.push_back(column(column::string_e, "name", 4, false));
            o_columns.push_back(column(column::uint_e, "ns_ttl", 5, false));
            o_columns.push_back(column(column::uuid_e, "root_server_id", 6, false));
            o_primary_key = column(column::uuid_e, "root_server_id", 6, false);
            
            o_initialised = true;
        }
    }
}

shared_ptr<row_root_server> row_root_server::get_by_root_server_id(connection &c, uuid root_server_id)
{
    init_static();
    return convert_row_type(instance.fetch_row(c, o_columns[5], root_server_id));
}



void row_root_server::delete_by_root_server_id(connection &c, uuid root_server_id)
{
    init_static();
    instance.delete_rows(c, o_columns[5], root_server_id);
}



uint row_root_server::get_addr_ttl() const
{
    return m_addr_ttl;
}

string row_root_server::get_ip_address() const
{
    return m_ip_address;
}

datetime row_root_server::get_last_contact_date_time() const
{
    return m_last_contact_date_time;
}

string row_root_server::get_name() const
{
    return m_name;
}

uint row_root_server::get_ns_ttl() const
{
    return m_ns_ttl;
}

uuid row_root_server::get_root_server_id() const
{
    return m_root_server_id;
}



void row_root_server::set_addr_ttl(uint v)
{
    m_addr_ttl = v;
}

void row_root_server::set_ip_address(string v)
{
    m_ip_address = v;
}

void row_root_server::set_last_contact_date_time(datetime v)
{
    m_last_contact_date_time = v;
}

void row_root_server::set_name(string v)
{
    m_name = v;
}

void row_root_server::set_ns_ttl(uint v)
{
    m_ns_ttl = v;
}

void row_root_server::set_root_server_id(uuid v)
{
    m_root_server_id = v;
}


