// 
// Copyright 2025 Andrew Haisley
// 
// This program is free software: you can redistribute it and/or modify it under the terms 
// of the GNU General Public License as published by the Free Software Foundation, either 
// version 3 of the License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
// See the GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License along with this program. 
// If not, see https://www.gnu.org/licenses/.
// 
/**
 * autogenerated by dbgen.py at 03:09PM on March 22, 2025, do not hand edit
 */

#include <boost/uuid/uuid_generators.hpp>

#include "row_dns_client.hpp"

using namespace adns;
using namespace db;
using namespace std;

mutex row_dns_client::o_lock;
vector<column> row_dns_client::o_columns;
atomic<bool> row_dns_client::o_initialised(false);
column row_dns_client::o_primary_key;
vector<foreign_key> row_dns_client::o_foreign_keys;

static row_dns_client instance;

static shared_ptr<row_dns_client> convert_row_type(row *r)
{
    return shared_ptr<row_dns_client>(static_cast<row_dns_client*>(r));
}

static vector<shared_ptr<row_dns_client>> convert_row_type(vector<row *> vr)
{
    vector<shared_ptr<row_dns_client>> res(vr.size());
    for (size_t i = 0; i < vr.size(); i++)
    {
        res[i] = shared_ptr<row_dns_client>(static_cast<row_dns_client*>(vr[i]));
    }
    return res;
}

    
row_dns_client::row_dns_client()
{
    m_connect_tcp_timeout_ms = 0;
    m_num_parallel_udp = 0;
    m_read_tcp_timeout_ms = 0;
    m_server_port = 0;
    m_total_timeout_ms = 0;
    m_udp_timeout_ms = 0;
    m_use_ip4 = false;
    m_use_ip6 = false;
    m_use_tcp = false;
    m_use_udp = false;
    m_wait_udp_response_ms = 0;
    m_write_tcp_timeout_ms = 0;
}

row_dns_client::~row_dns_client()
{
}

vector<shared_ptr<row_dns_client>> row_dns_client::get_rows(connection &conn)
{
    return convert_row_type(instance.fetch_rows(conn));
}

string row_dns_client::get_table_name() const
{
    return "dns_client";
}

table::table_t row_dns_client::get_table_id() const
{
    return table::dns_client_e;
}

row *row_dns_client::create_instance() const
{
    return new row_dns_client();
}

void row_dns_client::set_column_value(const column &c, int value)
{
    (void)value;
    THROW(row_exception, "no columns of type int found", c.get_position());
}

void row_dns_client::set_column_value(const column &c, bool value)
{
    switch (c.get_position())
    {
    case 8:
        m_use_ip4 = value;
        break;
    case 9:
        m_use_ip6 = value;
        break;
    case 10:
        m_use_tcp = value;
        break;
    case 11:
        m_use_udp = value;
        break;
    default:
        THROW(row_exception, "no columns of type bool found at position", c.get_position());
    }
}

void row_dns_client::set_column_value(const column &c, uint value)
{
    switch (c.get_position())
    {
    case 2:
        m_connect_tcp_timeout_ms = value;
        break;
    case 3:
        m_num_parallel_udp = value;
        break;
    case 4:
        m_read_tcp_timeout_ms = value;
        break;
    case 5:
        m_server_port = value;
        break;
    case 6:
        m_total_timeout_ms = value;
        break;
    case 7:
        m_udp_timeout_ms = value;
        break;
    case 12:
        m_wait_udp_response_ms = value;
        break;
    case 13:
        m_write_tcp_timeout_ms = value;
        break;
    default:
        THROW(row_exception, "no columns of type uint found at position", c.get_position());
    }
}

void row_dns_client::set_column_value(const column &c, octet value)
{
    (void)value;
    THROW(row_exception, "no columns of type octet found", c.get_position());
}

void row_dns_client::set_column_value(const column &c, uuid value)
{
    switch (c.get_position())
    {
    case 1:
        m_client_id = value;
        break;
    default:
        THROW(row_exception, "no columns of type uuid found at position", c.get_position());
    }
}

void row_dns_client::set_column_value(const column &c, const string &value)
{
    (void)value;
    THROW(row_exception, "no columns of type string found", c.get_position());
}

void row_dns_client::set_column_value(const column &c, const datetime &value)
{
    (void)value;
    THROW(row_exception, "no columns of type datetime found", c.get_position());
}

void row_dns_client::set_column_value(const column &c, const buffer &value)
{
    (void)value;
    THROW(row_exception, "no columns of type buffer found", c.get_position());
}

void row_dns_client::set_column_value(const column &c, nullable<int> value)
{
    (void)value;
    THROW(row_exception, "no columns of type int found", c.get_position());
}

void row_dns_client::set_column_value(const column &c, nullable<bool> value)
{
    (void)value;
    THROW(row_exception, "no columns of type bool found", c.get_position());
}

void row_dns_client::set_column_value(const column &c, nullable<uint> value)
{
    (void)value;
    THROW(row_exception, "no columns of type uint found", c.get_position());
}

void row_dns_client::set_column_value(const column &c, nullable<octet> value)
{
    (void)value;
    THROW(row_exception, "no columns of type octet found", c.get_position());
}

void row_dns_client::set_column_value(const column &c, nullable<uuid> value)
{
    (void)value;
    THROW(row_exception, "no columns of type uuid found", c.get_position());
}

void row_dns_client::set_column_value(const column &c, const nullable<string> &value)
{
    (void)value;
    THROW(row_exception, "no columns of type string found", c.get_position());
}

void row_dns_client::set_column_value(const column &c, const nullable<datetime> &value)
{
    (void)value;
    THROW(row_exception, "no columns of type datetime found", c.get_position());
}

void row_dns_client::set_column_value(const column &c, const nullable<buffer> &value)
{
    (void)value;
    THROW(row_exception, "no columns of type buffer found", c.get_position());
}

int row_dns_client::get_int_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type int found", c.get_name(), c.get_position());
}

bool row_dns_client::get_bool_column_value(const column &c) const
{
    switch (c.get_position())
    {
    case 8:
        return m_use_ip4;
    case 9:
        return m_use_ip6;
    case 10:
        return m_use_tcp;
    case 11:
        return m_use_udp;
    default:
        THROW(row_exception, "no columns of type bool found at position", c.get_name(), c.get_position());
    }
}

uint row_dns_client::get_uint_column_value(const column &c) const
{
    switch (c.get_position())
    {
    case 2:
        return m_connect_tcp_timeout_ms;
    case 3:
        return m_num_parallel_udp;
    case 4:
        return m_read_tcp_timeout_ms;
    case 5:
        return m_server_port;
    case 6:
        return m_total_timeout_ms;
    case 7:
        return m_udp_timeout_ms;
    case 12:
        return m_wait_udp_response_ms;
    case 13:
        return m_write_tcp_timeout_ms;
    default:
        THROW(row_exception, "no columns of type uint found at position", c.get_name(), c.get_position());
    }
}

octet row_dns_client::get_octet_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type octet found", c.get_name(), c.get_position());
}

uuid row_dns_client::get_uuid_column_value(const column &c) const
{
    switch (c.get_position())
    {
    case 1:
        return m_client_id;
    default:
        THROW(row_exception, "no columns of type uuid found at position", c.get_name(), c.get_position());
    }
}

const string &row_dns_client::get_string_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type string found", c.get_name(), c.get_position());
}

const datetime &row_dns_client::get_datetime_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type datetime found", c.get_name(), c.get_position());
}

const buffer &row_dns_client::get_buffer_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type buffer found", c.get_name(), c.get_position());
}

nullable<int> row_dns_client::get_nullable_int_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type int found", c.get_name(), c.get_position());
}

nullable<bool> row_dns_client::get_nullable_bool_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type bool found", c.get_name(), c.get_position());
}

nullable<uint> row_dns_client::get_nullable_uint_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type uint found", c.get_name(), c.get_position());
}

nullable<octet> row_dns_client::get_nullable_octet_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type octet found", c.get_name(), c.get_position());
}

nullable<uuid> row_dns_client::get_nullable_uuid_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type uuid found", c.get_name(), c.get_position());
}

const nullable<string> &row_dns_client::get_nullable_string_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type string found", c.get_name(), c.get_position());
}

const nullable<datetime> &row_dns_client::get_nullable_datetime_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type datetime found", c.get_name(), c.get_position());
}

const nullable<buffer> &row_dns_client::get_nullable_buffer_column_value(const column &c) const
{
    THROW(row_exception, "no columns of type buffer found", c.get_name(), c.get_position());
}

const vector<column> &row_dns_client::get_columns() const
{
    init_static();
    return o_columns;
}

const vector<foreign_key> &row_dns_client::get_foreign_keys() const
{
    init_static();
    return o_foreign_keys;
}

const column &row_dns_client::get_primary_key() const
{
    init_static();
    return o_primary_key;
}

uuid row_dns_client::get_primary_key_value() const
{
    return get_uuid_column_value(get_primary_key());
}

void row_dns_client::init_static()
{
    if (!o_initialised)
    {
        lock_guard<mutex> guard(o_lock);
        if (!o_initialised)
        {
            o_columns.push_back(column(column::uuid_e, "client_id", 1, false));
            o_primary_key = column(column::uuid_e, "client_id", 1, false);
            o_columns.push_back(column(column::uint_e, "connect_tcp_timeout_ms", 2, false));
            o_columns.push_back(column(column::uint_e, "num_parallel_udp", 3, false));
            o_columns.push_back(column(column::uint_e, "read_tcp_timeout_ms", 4, false));
            o_columns.push_back(column(column::uint_e, "server_port", 5, false));
            o_columns.push_back(column(column::uint_e, "total_timeout_ms", 6, false));
            o_columns.push_back(column(column::uint_e, "udp_timeout_ms", 7, false));
            o_columns.push_back(column(column::bool_e, "use_ip4", 8, false));
            o_columns.push_back(column(column::bool_e, "use_ip6", 9, false));
            o_columns.push_back(column(column::bool_e, "use_tcp", 10, false));
            o_columns.push_back(column(column::bool_e, "use_udp", 11, false));
            o_columns.push_back(column(column::uint_e, "wait_udp_response_ms", 12, false));
            o_columns.push_back(column(column::uint_e, "write_tcp_timeout_ms", 13, false));
            
            o_initialised = true;
        }
    }
}

shared_ptr<row_dns_client> row_dns_client::get_by_client_id(connection &c, uuid client_id)
{
    init_static();
    return convert_row_type(instance.fetch_row(c, o_columns[0], client_id));
}



void row_dns_client::delete_by_client_id(connection &c, uuid client_id)
{
    init_static();
    instance.delete_rows(c, o_columns[0], client_id);
}



uuid row_dns_client::get_client_id() const
{
    return m_client_id;
}

uint row_dns_client::get_connect_tcp_timeout_ms() const
{
    return m_connect_tcp_timeout_ms;
}

uint row_dns_client::get_num_parallel_udp() const
{
    return m_num_parallel_udp;
}

uint row_dns_client::get_read_tcp_timeout_ms() const
{
    return m_read_tcp_timeout_ms;
}

uint row_dns_client::get_server_port() const
{
    return m_server_port;
}

uint row_dns_client::get_total_timeout_ms() const
{
    return m_total_timeout_ms;
}

uint row_dns_client::get_udp_timeout_ms() const
{
    return m_udp_timeout_ms;
}

bool row_dns_client::get_use_ip4() const
{
    return m_use_ip4;
}

bool row_dns_client::get_use_ip6() const
{
    return m_use_ip6;
}

bool row_dns_client::get_use_tcp() const
{
    return m_use_tcp;
}

bool row_dns_client::get_use_udp() const
{
    return m_use_udp;
}

uint row_dns_client::get_wait_udp_response_ms() const
{
    return m_wait_udp_response_ms;
}

uint row_dns_client::get_write_tcp_timeout_ms() const
{
    return m_write_tcp_timeout_ms;
}



void row_dns_client::set_client_id(uuid v)
{
    m_client_id = v;
}

void row_dns_client::set_connect_tcp_timeout_ms(uint v)
{
    m_connect_tcp_timeout_ms = v;
}

void row_dns_client::set_num_parallel_udp(uint v)
{
    m_num_parallel_udp = v;
}

void row_dns_client::set_read_tcp_timeout_ms(uint v)
{
    m_read_tcp_timeout_ms = v;
}

void row_dns_client::set_server_port(uint v)
{
    m_server_port = v;
}

void row_dns_client::set_total_timeout_ms(uint v)
{
    m_total_timeout_ms = v;
}

void row_dns_client::set_udp_timeout_ms(uint v)
{
    m_udp_timeout_ms = v;
}

void row_dns_client::set_use_ip4(bool v)
{
    m_use_ip4 = v;
}

void row_dns_client::set_use_ip6(bool v)
{
    m_use_ip6 = v;
}

void row_dns_client::set_use_tcp(bool v)
{
    m_use_tcp = v;
}

void row_dns_client::set_use_udp(bool v)
{
    m_use_udp = v;
}

void row_dns_client::set_wait_udp_response_ms(uint v)
{
    m_wait_udp_response_ms = v;
}

void row_dns_client::set_write_tcp_timeout_ms(uint v)
{
    m_write_tcp_timeout_ms = v;
}


